### ISSUE TITLE
Flavor configuration can fail when clouds.yaml present with different credentials

### ISSUE THREAD

**Issue by priteau** [stackhpc/stackhpc-config-cookiecutter#12]
In one environment, we had an issue where the `*-config` repository started failing to apply some, but not all playbooks. The flavors playbook was affected, but the projects one wasn't. Flavor configuration requests were returning `401 Unauthorised` errors.

We discovered it was caused by the presence of a `clouds.yaml` file in the standard location. This file included a single cloud definition, with a `project_id` key for another project than the one being used to configure flavors (`admin`).

It seems that `openstacksdk` picks up this `project_id` even though we don't request to use a specific cloud. We then provide our own credentials, but they don't include `project_id`. We end up making requests as the `admin` user, but with the project from `clouds.yaml`.

The following message can be seen in Keystone logs (with `debug = True`):

```
DEBUG keystone.models.token_model [req-ac4b6199-ee9d-42cb-8de5-663e773b4ab6 - - - - -] User <user_id> has no access to project <project_id_from_clouds_yaml> _validate_project_scope /usr/lib/python3.6/site-packages/keystone/models/token_model.py:540
```

**Comment by markgoddard** [comment]
Bad openstacksdk
